description: "Registrations per day."

query:
  SELECT DATE_FORMAT(created_at, '%Y-%m-%d') AS day, COUNT(id) AS registered FROM units
    GROUP BY day ORDER BY day DESC
    LIMIT {days};

defaults:
  days: 30

access:
  - anonymous

views:
  chart: units_per_day_timeseries.go

cache:
  type: 1
  # expression parameters to use for caching
  keys: [days]
  # ttl in seconds
  ttl: 3600